sqlite3: &sqlite3
  adapter: sqlite3
  encoding: utf8

development:
  <<: *sqlite3
  database: "db/dev.sqlite3"

test:
  <<: *sqlite3
  database: "db/test.sqlite3"

production:
  <<: *sqlite3
  database: "db/prod.sqlite3"
