pid: tmp/thin.pid
timeout: 30
log: log/thin.log
# trace: true
max_conns: 1024
require: []
max_persistent_conns: 512
environment: development
servers: 2
daemonize: true
rackup: config.ru
port: 9292
address: 127.0.0.1
